project: 
  type: website
  
website: 
  title: "Seatbelts"
  navbar:
    left: 
      - href: paper.qmd
        text: "Paper"
      - href: slides.qmd
        text: "Slides"
format:
  html:
    theme: 
      dark: slate
      light: morph
        